//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Clientes
{
    public int id { get; set; }
    public string Documento { get; set; }
    public string Primer_nombre { get; set; }
    public string Segundo_nombre { get; set; }
    public string Primer_apellido { get; set; }
    public string Segundo_apellido { get; set; }
    public string Direccion { get; set; }
    public string Telefono_fijo { get; set; }
    public string Movil { get; set; }
    public string Email { get; set; }
    public int idTipoDocumento { get; set; }
    public int idCiudad { get; set; }

    public virtual Ciudades Ciudades { get; set; }
}
