//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class SigtiEntities : DbContext
{
    public SigtiEntities()
        : base("name=SigtiEntities")
    {
    }

   

    public virtual DbSet<Categoria> Categoria { get; set; }
    public virtual DbSet<Ciudades> Ciudades { get; set; }
    public virtual DbSet<Clientes> Clientes { get; set; }
    public virtual DbSet<Pais> Pais { get; set; }
    public virtual DbSet<SettingEntity> SettingEntity { get; set; }
    public virtual DbSet<SettingEntityTypeCat> SettingEntityTypeCat { get; set; }
}
