//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class SettingEntity
{
    public int SettingEntityId { get; set; }
    public string Code { get; set; }
    public string Value { get; set; }
    public string Description { get; set; }
    public bool IsCypher { get; set; }
    public bool IsActive { get; set; }
    public int SettingEntityTypeId { get; set; }

    public virtual SettingEntityTypeCat SettingEntityTypeCat { get; set; }
}
